package com.zlf.appmaster.model.stock;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE".
 */
public class Message {

    private Long id;
    private Long msgID;
    private Long senderUin;
    private Long receiverUin;
    private Integer msgType;
    private Long msgTypeID;
    private String data;
    private Integer dataType;
    private String msgTypeName;
    private Long msgTypeSeq;
    private Integer voiceStatus;
    private Integer imgStatus;
    private Integer delFlag;
    private String pushTitle;
    private String pushContent;
    private Integer version;
    private String device;
    private Long createTime;
    private Long updateTime;
    private String senderName;
    private Long clientID;
    private Integer direct;
    private Integer status;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, Long msgID, Long senderUin, Long receiverUin, Integer msgType, Long msgTypeID, String data, Integer dataType, String msgTypeName, Long msgTypeSeq, Integer voiceStatus, Integer imgStatus, Integer delFlag, String pushTitle, String pushContent, Integer version, String device, Long createTime, Long updateTime, String senderName, Long clientID, Integer direct, Integer status) {
        this.id = id;
        this.msgID = msgID;
        this.senderUin = senderUin;
        this.receiverUin = receiverUin;
        this.msgType = msgType;
        this.msgTypeID = msgTypeID;
        this.data = data;
        this.dataType = dataType;
        this.msgTypeName = msgTypeName;
        this.msgTypeSeq = msgTypeSeq;
        this.voiceStatus = voiceStatus;
        this.imgStatus = imgStatus;
        this.delFlag = delFlag;
        this.pushTitle = pushTitle;
        this.pushContent = pushContent;
        this.version = version;
        this.device = device;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.senderName = senderName;
        this.clientID = clientID;
        this.direct = direct;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMsgID() {
        return msgID;
    }

    public void setMsgID(Long msgID) {
        this.msgID = msgID;
    }

    public Long getSenderUin() {
        return senderUin;
    }

    public void setSenderUin(Long senderUin) {
        this.senderUin = senderUin;
    }

    public Long getReceiverUin() {
        return receiverUin;
    }

    public void setReceiverUin(Long receiverUin) {
        this.receiverUin = receiverUin;
    }

    public Integer getMsgType() {
        return msgType;
    }

    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    public Long getMsgTypeID() {
        return msgTypeID;
    }

    public void setMsgTypeID(Long msgTypeID) {
        this.msgTypeID = msgTypeID;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Integer getDataType() {
        return dataType;
    }

    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    public String getMsgTypeName() {
        return msgTypeName;
    }

    public void setMsgTypeName(String msgTypeName) {
        this.msgTypeName = msgTypeName;
    }

    public Long getMsgTypeSeq() {
        return msgTypeSeq;
    }

    public void setMsgTypeSeq(Long msgTypeSeq) {
        this.msgTypeSeq = msgTypeSeq;
    }

    public Integer getVoiceStatus() {
        return voiceStatus;
    }

    public void setVoiceStatus(Integer voiceStatus) {
        this.voiceStatus = voiceStatus;
    }

    public Integer getImgStatus() {
        return imgStatus;
    }

    public void setImgStatus(Integer imgStatus) {
        this.imgStatus = imgStatus;
    }

    public Integer getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    public String getPushTitle() {
        return pushTitle;
    }

    public void setPushTitle(String pushTitle) {
        this.pushTitle = pushTitle;
    }

    public String getPushContent() {
        return pushContent;
    }

    public void setPushContent(String pushContent) {
        this.pushContent = pushContent;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getDevice() {
        return device;
    }

    public void setDevice(String device) {
        this.device = device;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public String getSenderName() {
        return senderName;
    }

    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    public Long getClientID() {
        return clientID;
    }

    public void setClientID(Long clientID) {
        this.clientID = clientID;
    }

    public Integer getDirect() {
        return direct;
    }

    public void setDirect(Integer direct) {
        this.direct = direct;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}
